export Login from './Login/login';
export Register from './Login/register';
export DoctorDashboard  from './DoctorDashboard';
export PatientDashboard  from './PatientDashboard';
export Messages from './PatientComps/messages'
export PatientForm from './PatientComps/PatientForm'
export ApptConfirmation from './PatientComps/ApptConfirmation'
export PatientProfile from './PatientComps/PatientProfile'
export DoctorList from './PatientComps/DoctorList'
export Insurance from './PatientComps/Insurance'
export MedicalHistoryForm from './PatientComps/MedicalHistoryForm'
export EmergencyContactForm from './PatientComps/EmergencyContactForm'
export Appointments from './PatientComps/Appointments'